version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nodeapp-test.conf:/etc/nginx/conf.d/nodeapp-test.conf
    ports:
      - 80:80
    network_mode: host
